name: odda
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=4.5=1_gnu
  - ca-certificates=2021.5.30=ha878542_0
  - ld_impl_linux-64=2.35.1=h7274673_9
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.3.0=h5101ec6_17
  - libgomp=9.3.0=h5101ec6_17
  - libprotobuf=3.17.2=h4ff587b_1
  - libstdcxx-ng=9.3.0=hd4cf53a_17
  - ncurses=6.2=he6710b0_1
  - openssl=1.1.1l=h7f8727e_0
  - pandoc=2.14.2=h7f98852_0
  - pip=21.1.3=py36h06a4308_0
  - protobuf=3.17.2=py36h295c915_0
  - python=3.6.13=h12debd9_1
  - python_abi=3.6=2_cp36m
  - readline=8.1=h27cfd23_0
  - setuptools=52.0.0=py36h06a4308_0
  - six=1.16.0=pyhd3eb1b0_0
  - sqlite=3.36.0=hc218d9a_0
  - tk=8.6.10=hbc83047_0
  - wheel=0.36.2=pyhd3eb1b0_0
  - xz=5.2.5=h7b6447c_0
  - zlib=1.2.11=h7b6447c_3
  - pip:
    - absl-py==0.12.0
    - argcomplete==1.12.2
    - astor==0.8.1
    - cached-property==1.5.2
    - cachetools==4.2.1
    - certifi==2020.12.5
    - cffi==1.14.6
    - chardet==4.0.0
    - click==8.0.1
    - crcmod==1.7
    - cycler==0.10.0
    - ecdsa==0.17.0
    - fire==0.4.0
    - flatbuffers==2.0
    - future-fstrings==1.2.0
    - gast==0.2.2
    - google-auth==1.28.1
    - google-auth-oauthlib==0.4.4
    - google-pasta==0.2.0
    - grpcio==1.37.0
    - h5py==2.10.0
    - idna==2.10
    - intelhex==2.3.0
    - joblib==1.0.1
    - keras-applications==1.0.8
    - keras-preprocessing==1.1.2
    - keras2onnx==1.7.0
    - kiwisolver==1.3.1
    - libusb1==1.9.3
    - mako==1.1.4
    - markdown==3.3.4
    - markupsafe==2.0.1
    - matplotlib==3.3.4
    - numpy==1.19.5
    - oauthlib==3.1.0
    - onnx==1.9.0
    - onnxconverter-common==1.7.0
    - onnxmltools==1.7.0
    - onnxruntime==1.8.1
    - opt-einsum==3.3.0
    - ortools==7.5.7466
    - packaging==20.9
    - pandas==1.1.5
    - pc-ble-driver-py==0.15.0
    - piccata==2.0.1
    - pillow==8.2.0
    - pthflops==0.4.1
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycparser==2.20
    - pyelftools==0.27
    - pyparsing==2.4.7
    - pyserial==3.5
    - pyspinel==1.0.3
    - python-dateutil==2.8.1
    - pytz==2021.1
    - pyyaml==5.4.1
    - requests==2.25.1
    - requests-oauthlib==1.3.0
    - rsa==4.7.2
    - scikit-learn==0.24.1
    - scipy==1.5.4
    - seaborn==0.11.2
    - skl2onnx==1.9.0
    - soundfile==0.10.3.post1
    - tensorboard==2.0.2
    - tensorflow-estimator==2.0.1
    - tensorflow-gpu==2.0.0
    - termcolor==1.1.0
    - threadpoolctl==2.1.0
    - torch==1.4.0
    - torchaudio==0.4.0
    - torchsummary==1.5.1
    - torchvision==0.5.0
    - tqdm==4.60.0
    - urllib3==1.26.4
    - werkzeug==1.0.1
    - wrapt==1.12.1
prefix: path/to/miniconda3/envs/odda
